#include <stddef.h>
#include <stdint.h>
#include <string.h>
#include "nosfs_pub.h"

/* Generated by the Makefile (xxd -i) */
#include "init_bin.h"
#include "login_bin.h"

/* tiny helpers */
static int streq(const char *a, const char *b) {
    return a && b && strcmp(a, b) == 0;
}
static int streq_any(const char *p, const char *a, const char *b) {
    return streq(p, a) || streq(p, b);
}

/* Public, minimal NOSFS read API used by the loader.
   We expose two built-in agent images so boot works even before a full nosfs. */
int nosfs_read_file(const char *path, const void **out, size_t *out_sz)
{
    if (!out || !out_sz || !path) return -2; /* ENOENT-ish */

    /* Tolerate optional leading slash and multiple spellings */
    if (streq_any(path, "/agents/init.mo2", "agents/init.mo2")) {
        *out    = (const void*)init_bin;
        *out_sz = (size_t)init_bin_len;
        return 0;
    }
    if (streq_any(path, "/agents/login.mo2", "agents/login.mo2")) {
        *out    = (const void*)login_bin;
        *out_sz = (size_t)login_bin_len;
        return 0;
    }

    /* Not found in the built-in set. Higher layers may provide a richer nosfs. */
    *out = NULL; *out_sz = 0;
    return -2; /* ENOENT */
}
