// kernel/nosfs_pub.c
#include <stddef.h>
#include <stdint.h>
#include <string.h>

// These are generated by the Makefile's xxd rules.
#include "init_bin.h"
#if __has_include("login_bin.h")
#  include "login_bin.h"
#  define HAVE_LOGIN_BIN 1
#endif

// Return 0 on success, <0 on error
int nosfs_get_file(const char* path, const void** out_ptr, size_t* out_sz) {
    if (!path || !out_ptr || !out_sz) return -22; // EINVAL

    // Accept both with and without leading slash
    const char* p = path;
    if (p[0] == '/') ++p;

    if (strcmp(p, "agents/init.mo2") == 0) {
        *out_ptr = (const void*)init_bin;
        *out_sz  = (size_t)init_bin_len;
        return 0;
    }
#ifdef HAVE_LOGIN_BIN
    if (strcmp(p, "agents/login.mo2") == 0) {
        *out_ptr = (const void*)login_bin;
        *out_sz  = (size_t)login_bin_len;
        return 0;
    }
#endif

    return -2; // ENOENT
}
